# Generated by Django 5.2.7 on 2025-10-29 16:12

import django.db.models.deletion
import payroll.models.files
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='EMPLOYEE', max_length=20)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cnp', models.CharField(max_length=13, unique=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='payroll.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=128)),
                ('period', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='CREATED', max_length=16)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_keys', to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, help_text='1st of the month')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, help_text='1st of month')),
                ('working_days', models.PositiveSmallIntegerField()),
                ('vacation_days', models.PositiveSmallIntegerField(default=0)),
                ('bonus_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salary_to_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='payroll.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollrun')),
            ],
        ),
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MANAGER_CSV', 'Manager CSV'), ('EMPLOYEE_PDF', 'Employee PDF')], max_length=20)),
                ('file', models.FileField(upload_to=payroll.models.files.archive_upload_path)),
                ('period', models.DateField(db_index=True, help_text='First day of month')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_files', to='payroll.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_files', to='payroll.employee')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='payroll.payrollrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'role'], name='payroll_emp_departm_15471f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['manager'], name='payroll_emp_manager_79d1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['endpoint', 'key'], name='payroll_ide_endpoin_665ccc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='idempotencykey',
            unique_together={('endpoint', 'key')},
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['period', 'manager'], name='payroll_pay_period_1f7d96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('manager', 'period')},
        ),
        migrations.AddIndex(
            model_name='payrollline',
            index=models.Index(fields=['period', 'employee'], name='payroll_pay_period_bb9859_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollline',
            index=models.Index(fields=['run'], name='payroll_pay_run_id_ca850f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollline',
            unique_together={('run', 'employee')},
        ),
        migrations.AddIndex(
            model_name='filerecord',
            index=models.Index(fields=['category', 'year', 'month'], name='payroll_fil_categor_75c802_idx'),
        ),
    ]
